async page => {
  const base = await page.evaluate(() => location.origin);
  const checks = [];
  const errors = [];
  const check = (condition, message) => { if (!condition) throw new Error(message); checks.push(message); };
  page.on('pageerror', error => errors.push(error.message));
  const first = iso => page.waitForFunction(value => document.querySelector('#cron-runs time')?.getAttribute('datetime') === value, iso);
  const expression = async value => { await page.locator('#cron-expression').fill(value); await page.locator('#cron-run').click(); };
  await page.setViewportSize({ width: 1440, height: 1050 });
  await page.goto(`${base}/tools/cron/`);
  await page.waitForSelector('#cron-runs tr:nth-child(10)');
  check(await page.locator('h1').textContent() === 'Cron 表达式测试器', 'Cron is integrated into the existing tool shell');
  check(await page.locator('#cron-fields .cron-field').count() === 5, 'all five fields have explanations');
  await page.locator('#cron-from').fill('2026-09-27T00:00');
  await expression('*/5 * * * *');
  await first('2026-09-27T00:05:00.000Z');
  check((await page.locator('#cron-runs tr').first().textContent()).includes('08:05:00'), 'UTC run and Beijing preview appear side by side');
  check((await page.locator('#cron-description').textContent()).includes('5 分钟'), 'Cron description is in Chinese');
  await expression('0 0 * * 1');
  await first('2026-09-28T00:00:00.000Z');
  await page.locator('#cron-mode').selectOption('cloudflare');
  await first('2026-10-04T00:00:00.000Z');
  check(await page.locator('#cron-zone').isDisabled(), 'Cloudflare mode locks execution to UTC');
  check((await page.locator('#cron-syntax-hint').textContent()).includes('基础子集'), 'Cloudflare restrictions are visible next to the input');
  await expression('0 0 1 * MON');
  await page.waitForFunction(() => document.querySelector('#cron-feedback').textContent.includes('同时限制日期和星期'));
  check(await page.locator('#cron-results').isHidden(), 'invalid Cloudflare input clears stale results');
  await expression('59 23 LW * *');
  await page.waitForFunction(() => document.querySelector('#cron-feedback').textContent.includes('不支持'));
  check(await page.locator('#cron-expression').getAttribute('aria-invalid') === 'true', 'unsupported dialect extensions show accessible errors');
  await page.locator('#cron-mode').selectOption('unix');
  await expression('0 0 1 * MON');
  await first('2026-09-28T00:00:00.000Z');
  check((await page.locator('#cron-runs tr').nth(1).textContent()).includes('2026-10-01'), 'Unix DOM and DOW use OR semantics');
  await expression('0 9 * * *');
  await page.locator('#cron-zone').selectOption('Asia/Shanghai');
  await first('2026-09-27T01:00:00.000Z');
  check((await page.locator('#cron-description-note').textContent()).includes('Asia/Shanghai'), 'schedule timezone changes interpretation');
  await page.locator('#cron-display-zone').selectOption('UTC');
  await first('2026-09-27T01:00:00.000Z');
  await page.waitForFunction(() => document.querySelector('#cron-display-title').textContent.includes('UTC'));
  check((await page.locator('#cron-runs tr').first().textContent()).includes('01:00:00'), 'display timezone changes presentation without changing the instant');
  await page.locator('#cron-zone').selectOption('custom');
  await page.locator('#cron-custom-zone').fill('Mars/Base');
  await page.locator('#cron-run').click();
  await page.waitForFunction(() => document.querySelector('#cron-feedback').textContent.includes('时区无效'));
  check(await page.locator('#cron-results').isHidden(), 'invalid custom timezone is rejected');
  await page.locator('#cron-zone').selectOption('UTC');
  await expression('0 0 31 FEB *');
  await page.waitForFunction(() => document.querySelector('#cron-feedback').textContent.includes('没有可执行日期'));
  check(true, 'impossible calendar dates fail without blocking the page');
  await page.locator('[data-cron-preset="*/5 * * * *"]').click();
  await first('2026-09-27T00:05:00.000Z');
  await page.evaluate(() => { Object.defineProperty(navigator, 'clipboard', { configurable: true, value: { writeText: async value => { window.cronCopied = value; } } }); });
  await page.locator('#cron-copy-expression').click();
  check(await page.evaluate(() => window.cronCopied === '*/5 * * * *'), 'copy expression preserves the five fields');
  await page.locator('#cron-copy-results').click();
  check(await page.evaluate(() => window.cronCopied.includes('2026-09-27T00:05:00.000Z') && window.cronCopied.split('\n').length === 11), 'copy results includes ten unambiguous UTC instants');
  await expression('<img> * * * *');
  await page.waitForSelector('#cron-feedback.error');
  check(await page.locator('#cron-feedback img').count() === 0, 'invalid markup cannot render as HTML');
  await page.evaluate(() => { window.cronOriginalWorker = window.Worker; window.Worker = class { postMessage() {} terminate() {} }; });
  await expression('*/5 * * * *');
  await page.waitForFunction(() => document.querySelector('#cron-feedback').textContent.includes('超过 3 秒'), null, { timeout: 7000 });
  check(await page.locator('#cron-now').isEnabled(), 'timeout releases the calculation without locking the UI');
  await page.evaluate(() => { window.Worker = window.cronOriginalWorker; });
  await page.locator('#cron-run').click();
  await first('2026-09-27T00:05:00.000Z');
  check(await page.locator('#cron-runs tr').count() === 10, 'Cron calculation recovers after a timeout');
  for (const width of [375, 768, 1280]) {
    await page.setViewportSize({ width, height: 900 });
    check(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), `Cron page has no horizontal overflow at ${width}px`);
  }
  await page.reload();
  await page.waitForSelector('#cron-runs tr:nth-child(10)');
  check(await page.locator('#cron-expression').inputValue() === '*/5 * * * *', 'Cron input remains ephemeral after reload');
  check(errors.length === 0, `no Cron browser errors: ${errors.join(', ')}`);
  return { passed: checks.length, checks };
}
