async page => {
  await page.locator('.brand').first().waitFor({ state: 'attached' });
  const base = await page.locator('.brand').first().getAttribute('href');
  const origin = await page.evaluate(() => location.origin);
  const site = origin + base;
  const checks = [];
  const errors = [];
  const failed = [];
  const apiRequests = [];
  const workerRequests = [];
  const check = (value, message) => { if (!value) throw new Error(message); checks.push(message); };
  page.on('pageerror', error => errors.push(error.message));
  page.on('response', response => { if (response.status() >= 400) failed.push(response.url()); });
  page.on('request', request => {
    if (request.url().includes('/api/')) apiRequests.push(request.url());
    if (/\/(?:regex-worker|cron-core)-[^/]+\.js/.test(request.url())) workerRequests.push(request.url());
  });
  await page.emulateMedia({ reducedMotion: 'reduce' });
  await page.setViewportSize({ width: 1440, height: 1000 });
  await page.goto(site);
  check(await page.locator('.tool-card').count() === 9, 'Pages directory lists nine local tools');
  check((await page.locator('.pages-notice').textContent()).includes('静态版'), 'static deployment capabilities are explained');
  for (const id of ['outlook', 'ip', 'domain']) check(await page.locator(`a[href="${base}tools/${id}/"]`).count() === 0, `${id} is not advertised as functional in the static directory`);
  const favorite = page.locator('[data-favorite="jwt"]');
  if (await favorite.getAttribute('aria-pressed') !== 'true') await favorite.click();
  await page.locator(`.sidebar a[href="${base}?view=favorites"]`).click();
  check((await page.locator('#tool-grid').textContent()).includes('JWT'), 'favorites navigation keeps the base path');
  await page.goto(site + 'tools/jwt/');
  await page.locator('#jwt-example').click();
  check((await page.locator('#jwt-feedback').textContent()).includes('解码完成'), 'JWT runs from a deep Pages URL');
  await page.locator('.back-link').click();
  check(page.url() === site, 'back link returns to the project homepage');
  await page.goto(site + 'tools/json/');
  await page.locator('[data-action="sample"]').click();
  check((await page.locator('#output').inputValue()).includes('Daykit'), 'JSON works');
  await page.goto(site + 'tools/encode/');
  await page.locator('[data-action="sample"]').click();
  check((await page.locator('#output').inputValue()).length > 0, 'encoding works');
  await page.goto(site + 'tools/timestamp/');
  await page.locator('#timestamp-input').fill('0');
  await page.locator('[data-action="to-date"]').click();
  check((await page.locator('#date-results').textContent()).includes('1970-01-01'), 'timestamp conversion works');
  await page.goto(site + 'tools/diff/');
  await page.locator('[data-diff-action="sample"]').click();
  check(await page.locator('.diff-row').count() > 0, 'Diff works');
  await page.goto(site + 'tools/config/');
  await page.locator('#config-sample').click();
  check((await page.locator('#config-output').inputValue()).includes('Daykit'), 'config dependencies load under the base path');
  await page.goto(site + 'tools/curl/');
  await page.locator('[data-curl-action="sample"]').click();
  check((await page.locator('#curl-code').inputValue()).includes('fetch('), 'cURL conversion works');
  await page.goto(site + 'tools/regex/');
  await page.locator('#regex-sample').click();
  await page.locator('.regex-match').first().waitFor();
  check(await page.locator('.regex-match').count() === 2, 'regex worker loads and returns matches');
  await page.goto(site + 'tools/cron/');
  await page.locator('#cron-runs tr:nth-child(10)').waitFor();
  check(await page.locator('#cron-runs tr').count() === 10, 'Cron worker loads and returns scheduled times');
  check(workerRequests.length >= 2 && workerRequests.every(url => url.startsWith(site + 'assets/')), 'browser worker URLs use the project base path');
  await page.keyboard.press('Control+k');
  await page.locator('#quick-search').fill('Base64');
  await page.locator('#quick-search').press('Enter');
  await page.waitForURL('**/tools/encode/');
  check(page.url() === site + 'tools/encode/', 'quick search preserves the project prefix');
  for (const id of ['outlook', 'ip', 'domain']) {
    await page.goto(site + `tools/${id}/`);
    check((await page.locator('.pages-notice').textContent()).includes('需要 Cloudflare Worker'), `${id} direct link shows deployment guidance`);
    check(await page.locator('#mail-account, #network-input').count() === 0, `${id} does not collect unsupported input`);
  }
  await page.goto(site + '404.html');
  check(await page.locator('a').getAttribute('href') === base, '404 recovery link uses the base path');
  await page.goto(site);
  await page.setViewportSize({ width: 375, height: 900 });
  await page.getByRole('button', { name: '打开导航菜单' }).click();
  await page.locator(`#mobile-dialog a[href="${base}tools/jwt/"]`).click();
  await page.locator('#jwt-example').click();
  check(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), 'mobile navigation and JWT layout fit the viewport');
  check(apiRequests.length === 0, 'Pages mode never calls missing API endpoints');
  check(failed.length === 0, `all resources load: ${failed.join(', ')}`);
  check(errors.length === 0, `no Pages JavaScript errors: ${errors.join(', ')}`);
  return { passed: checks.length, base, checks };
}
