async page => {
  const base = await page.evaluate(() => location.origin);
  const checks = [];
  const errors = [];
  const check = (condition, message) => { if (!condition) throw new Error(message); checks.push(message); };
  page.on('pageerror', error => errors.push(error.message));
  const sample = async () => {
    await page.locator('#regex-sample').click();
    await page.waitForFunction(() => document.querySelector('.regex-match-value')?.textContent === 'Ada Lovelace 1815');
  };
  await page.setViewportSize({ width: 1440, height: 1050 });
  await page.goto(`${base}/tools/regex/`);
  await page.locator('#regex-pattern').waitFor();
  check(await page.getByRole('heading', { name: '正则表达式测试器', exact: true }).isVisible(), 'regex tester is integrated in the original shell');
  await page.locator('#regex-pattern').fill('(?<word>[A-Za-z]+)');
  await page.locator('#regex-flags').fill('gi');
  await page.locator('#regex-text').fill('Hello HELLO 123');
  await page.waitForFunction(() => document.querySelectorAll('.regex-match').length === 2);
  check(await page.locator('.regex-match').count() === 2, 'global matching lists every match');
  check((await page.locator('#regex-summary').textContent()).includes('2 个匹配'), 'summary reports match count');
  check(await page.locator('.regex-highlight mark').count() === 2, 'highlight safely marks matched text');
  check((await page.locator('.regex-match-groups').first().textContent()).includes('word'), 'named capture group is rendered');
  await page.locator('#regex-pattern').fill('[');
  await page.waitForSelector('#regex-feedback.error');
  check((await page.locator('#regex-feedback').textContent()).includes('无效'), 'invalid regex reports a clear error');
  check(await page.locator('#regex-pattern').getAttribute('aria-invalid') === 'true', 'invalid regex has an accessible error state');
  await sample();
  check(await page.locator('.regex-match').count() === 2, 'sample produces capture matches');
  await page.evaluate(() => { Object.defineProperty(navigator, 'clipboard', { configurable: true, value: { writeText: async text => { window.regexCopied = text; } } }); });
  await page.locator('[data-regex-copy]').first().click();
  check(await page.evaluate(() => window.regexCopied === 'Ada Lovelace 1815'), 'match copy action copies the full value');
  await page.locator('#regex-pattern').fill('<[^>]+>');
  await page.locator('#regex-flags').fill('g');
  await page.locator('#regex-text').fill('<img src=x onerror="window.regexUnsafe=true">');
  await page.waitForFunction(() => document.querySelectorAll('.regex-highlight mark').length === 1);
  check(await page.locator('#regex-highlight img, #regex-matches img').count() === 0, 'matched HTML remains escaped in highlight and capture details');
  check(await page.evaluate(() => window.regexUnsafe !== true), 'matched markup cannot execute');
  await page.locator('#regex-pattern').fill('a');
  await page.locator('#regex-text').fill('a'.repeat(1200));
  await page.waitForFunction(() => document.querySelectorAll('.regex-match').length === 200);
  check((await page.locator('#regex-result-meta').textContent()).includes('至少 1,000'), 'matching stops at the documented cap');
  check(await page.locator('.regex-match').count() === 200, 'large results only render the first 200 detail rows');
  await page.locator('#regex-text').fill('a'.repeat(1_000_001));
  await page.waitForSelector('#regex-feedback.error');
  check((await page.locator('#regex-feedback').textContent()).includes('过长'), 'oversized text is rejected');
  await page.locator('#regex-text').fill('a'.repeat(100) + '!');
  await page.locator('#regex-pattern').fill('^(a|aa)+$');
  await page.locator('#regex-flags').fill('');
  await page.locator('#regex-run').click();
  await page.waitForFunction(() => document.querySelector('#regex-feedback').textContent.includes('超过 1 秒'), null, { timeout: 8000 });
  check(await page.locator('#regex-clear').isEnabled(), 'expensive expression times out without freezing the page');
  await sample();
  check(await page.locator('.regex-match').count() === 2, 'matching recovers after worker timeout');
  await page.locator('#regex-text').fill('a'.repeat(100) + '!');
  await page.locator('#regex-pattern').fill('^(a|aa)+$');
  await page.locator('#regex-run').click();
  await page.locator('#regex-clear').click();
  await page.waitForTimeout(1200);
  check(await page.locator('#regex-feedback').textContent() === '' && await page.locator('.regex-match').count() === 0, 'clear cancels active work and prevents stale timeout updates');
  for (const width of [375, 768, 1280]) {
    await page.setViewportSize({ width, height: 900 });
    await page.goto(`${base}/tools/regex/`);
    await sample();
    check(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), `regex has no horizontal overflow at ${width}px`);
  }
  await page.reload();
  await page.locator('#regex-pattern').waitFor();
  check(await page.locator('#regex-text').inputValue() === '', 'test text is not retained after reload');
  check(errors.length === 0, `no regex browser errors: ${errors.join(', ')}`);
  return { passed: checks.length, checks };
}
